### ISSUE TITLE
Issue loading the .rb file

### ISSUE THREAD

**Issue by ruchim** [notionparallax/Waffle-printer#2]
Is there a .rb file missing from the repo? I receive this error: ruby: No such file or directory
Perhaps I'm missing the obvious, any help is appreciated. Thanks in advance!

**Comment by notionparallax** [comment]
Can you post the full stack trace please?

**Comment by notionparallax** [comment]
@ruchim you are right, the .rb file is missing :(

@dawil, do you still have that file on your computer? I gave my laptop back when I left that job.

**Comment by Dawil** [comment]
That's unexpected. I'll check my laptop when I get home.

**Comment by notionparallax** [comment]
@ruchim try it now ;)
